export const GET_MEDIA_ITEMS = 'GET_MEDIA_ITEMS';
export const SAVE_MEDIA_ITEM = 'SAVE_MEDIA_ITEM';
export const DELETE_MEDIA_ITEM = 'DELETE_MEDIA_ITEM';
export const EDIT_MEDIA_ITEM = 'EDIT_MEDIA_ITEM';
export const SELECTED_TAB_CHANGED = 'SELECTED_TAB_CHANGED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
